name: flutter_module
description: A flutter module with a counter that can be manipulated from the host application.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.12
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^10.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/
  module:
    androidX: true
    androidPackage: com.example.flutter_module_rn
    iosBundleIdentifier: com.example.flutterModuleRn
