// Autogenerated from Pigeon (v10.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}
/// Generated class from Pigeon that represents Flutter messages that can be called from Swift.
class FlutterCounterApi {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  func setText(text textArg: String, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_module.FlutterCounterApi.setText", binaryMessenger: binaryMessenger)
    channel.sendMessage([textArg] as [Any?]) { _ in
      completion()
    }
  }
  func setScreen(screen screenArg: String, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_module.FlutterCounterApi.setScreen", binaryMessenger: binaryMessenger)
    channel.sendMessage([screenArg] as [Any?]) { _ in
      completion()
    }
  }
  func setClicks(value valueArg: Int64, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_module.FlutterCounterApi.setClicks", binaryMessenger: binaryMessenger)
    channel.sendMessage([valueArg] as [Any?]) { _ in
      completion()
    }
  }
  func setTheme(theme themeArg: String, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_module.FlutterCounterApi.setTheme", binaryMessenger: binaryMessenger)
    channel.sendMessage([themeArg] as [Any?]) { _ in
      completion()
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HostCounterApi {
  func setText(text: String) throws
  func setScreen(screen: String) throws
  func setClicks(value: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HostCounterApiSetup {
  /// The codec used by HostCounterApi.
  /// Sets up an instance of `HostCounterApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HostCounterApi?) {
    let setTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_module.HostCounterApi.setText", binaryMessenger: binaryMessenger)
    if let api = api {
      setTextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let textArg = args[0] as! String
        do {
          try api.setText(text: textArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setTextChannel.setMessageHandler(nil)
    }
    let setScreenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_module.HostCounterApi.setScreen", binaryMessenger: binaryMessenger)
    if let api = api {
      setScreenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let screenArg = args[0] as! String
        do {
          try api.setScreen(screen: screenArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setScreenChannel.setMessageHandler(nil)
    }
    let setClicksChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_module.HostCounterApi.setClicks", binaryMessenger: binaryMessenger)
    if let api = api {
      setClicksChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        do {
          try api.setClicks(value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setClicksChannel.setMessageHandler(nil)
    }
  }
}
